insert into departamentos (nombre) values ("Ventas");
insert into departamentos (nombre) values ("Recursos Humanos");
iNSERT INTO empleados (nombre, apellido, edad, salario, correo_electronico, departamentos_id) values ("Ana", "Rodriguez",28,3000.00,"anarodriguez@mail.com",1); 
iNSERT INTO empleados (nombre, apellido, edad, salario, correo_electronico, departamentos_id) values ("Carlos", "Lopez",32,3200.50,"carloslopez@mail.com",2); 
describe empleados;
iNSERT INTO empleados (nombre, apellido, edad, salario, correo_electronico, departamentos_id) values ("Laura", "Perez",26,2800.75,"lauraperez@mail.com",1); 
iNSERT INTO empleados (nombre, apellido, edad, salario, correo_electronico, departamentos_id) values ("Martin", "Gonzalez",30,3100.25,"martingonzalez@mail.com",2); 
alter table empleados add foreign key (departamentos_id) references departamentos(id); 
use mi_db;
alter table empleados modify fecha_contratacion date default (current_date);
delete from empleados where departamentos_id=1;
delete from empleados where departamentos_id=2;
set sql_safe_updates=0;
UPDATE empleados SET salario = salario * 1.1 WHERE nombre = 'Ana';
select salario from empleados where nombre='Ana';
insert into departamentos (nombre) values ("Contabilidad");
update empleados set departamentos_id=3 where nombre='Carlos';
delete from empleados where nombre = 'Laura';
select * from empleados;
select * from departamentos;